// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(voice_coreFFI)
import voice_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_voice_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_voice_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol SttSessionProtocol : AnyObject {
    
    func bufferDurationSeconds()  -> Double
    
    func chunkCount()  -> UInt32
    
    func finalize()  -> TranscriptionResult
    
    func id()  -> String
    
    func modelKey()  -> String
    
    func processChunk(samples: [Float])  -> [TranscriptionChunk]
    
    func reset() 
    
    func setChunk(chunk: TranscriptionChunk) 
    
    func status()  -> String
    
}

open class SttSession:
    SttSessionProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    /// This constructor can be used to instantiate a fake object.
    /// - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    ///
    /// - Warning:
    ///     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_voice_core_fn_clone_sttsession(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_voice_core_fn_free_sttsession(pointer, $0) }
    }

    

    
open func bufferDurationSeconds() -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_buffer_duration_seconds(self.uniffiClonePointer(),$0
    )
})
}
    
open func chunkCount() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_chunk_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func finalize() -> TranscriptionResult {
    return try!  FfiConverterTypeTranscriptionResult.lift(try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_finalize(self.uniffiClonePointer(),$0
    )
})
}
    
open func id() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_id(self.uniffiClonePointer(),$0
    )
})
}
    
open func modelKey() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_model_key(self.uniffiClonePointer(),$0
    )
})
}
    
open func processChunk(samples: [Float]) -> [TranscriptionChunk] {
    return try!  FfiConverterSequenceTypeTranscriptionChunk.lift(try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_process_chunk(self.uniffiClonePointer(),
        FfiConverterSequenceFloat.lower(samples),$0
    )
})
}
    
open func reset() {try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_reset(self.uniffiClonePointer(),$0
    )
}
}
    
open func setChunk(chunk: TranscriptionChunk) {try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_set_chunk(self.uniffiClonePointer(),
        FfiConverterTypeTranscriptionChunk.lower(chunk),$0
    )
}
}
    
open func status() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voice_core_fn_method_sttsession_status(self.uniffiClonePointer(),$0
    )
})
}
    

}

public struct FfiConverterTypeSttSession: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SttSession

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SttSession {
        return SttSession(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SttSession) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SttSession {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SttSession, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




public func FfiConverterTypeSttSession_lift(_ pointer: UnsafeMutableRawPointer) throws -> SttSession {
    return try FfiConverterTypeSttSession.lift(pointer)
}

public func FfiConverterTypeSttSession_lower(_ value: SttSession) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSttSession.lower(value)
}


public struct AiResponse {
    public var content: String
    public var thinking: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(content: String, thinking: String) {
        self.content = content
        self.thinking = thinking
    }
}



extension AiResponse: Equatable, Hashable {
    public static func ==(lhs: AiResponse, rhs: AiResponse) -> Bool {
        if lhs.content != rhs.content {
            return false
        }
        if lhs.thinking != rhs.thinking {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(content)
        hasher.combine(thinking)
    }
}


public struct FfiConverterTypeAiResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AiResponse {
        return
            try AiResponse(
                content: FfiConverterString.read(from: &buf), 
                thinking: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AiResponse, into buf: inout [UInt8]) {
        FfiConverterString.write(value.content, into: &buf)
        FfiConverterString.write(value.thinking, into: &buf)
    }
}


public func FfiConverterTypeAiResponse_lift(_ buf: RustBuffer) throws -> AiResponse {
    return try FfiConverterTypeAiResponse.lift(buf)
}

public func FfiConverterTypeAiResponse_lower(_ value: AiResponse) -> RustBuffer {
    return FfiConverterTypeAiResponse.lower(value)
}


public struct ChatMessage {
    public var role: String
    public var content: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(role: String, content: String) {
        self.role = role
        self.content = content
    }
}



extension ChatMessage: Equatable, Hashable {
    public static func ==(lhs: ChatMessage, rhs: ChatMessage) -> Bool {
        if lhs.role != rhs.role {
            return false
        }
        if lhs.content != rhs.content {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(role)
        hasher.combine(content)
    }
}


public struct FfiConverterTypeChatMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatMessage {
        return
            try ChatMessage(
                role: FfiConverterString.read(from: &buf), 
                content: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ChatMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.role, into: &buf)
        FfiConverterString.write(value.content, into: &buf)
    }
}


public func FfiConverterTypeChatMessage_lift(_ buf: RustBuffer) throws -> ChatMessage {
    return try FfiConverterTypeChatMessage.lift(buf)
}

public func FfiConverterTypeChatMessage_lower(_ value: ChatMessage) -> RustBuffer {
    return FfiConverterTypeChatMessage.lower(value)
}


public struct SttModelInfo {
    public var key: String
    public var displayName: String
    public var description: String
    public var sizeBytes: Int64
    public var requiresAppleSilicon: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, displayName: String, description: String, sizeBytes: Int64, requiresAppleSilicon: Bool) {
        self.key = key
        self.displayName = displayName
        self.description = description
        self.sizeBytes = sizeBytes
        self.requiresAppleSilicon = requiresAppleSilicon
    }
}



extension SttModelInfo: Equatable, Hashable {
    public static func ==(lhs: SttModelInfo, rhs: SttModelInfo) -> Bool {
        if lhs.key != rhs.key {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.sizeBytes != rhs.sizeBytes {
            return false
        }
        if lhs.requiresAppleSilicon != rhs.requiresAppleSilicon {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(key)
        hasher.combine(displayName)
        hasher.combine(description)
        hasher.combine(sizeBytes)
        hasher.combine(requiresAppleSilicon)
    }
}


public struct FfiConverterTypeSttModelInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SttModelInfo {
        return
            try SttModelInfo(
                key: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                sizeBytes: FfiConverterInt64.read(from: &buf), 
                requiresAppleSilicon: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SttModelInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterInt64.write(value.sizeBytes, into: &buf)
        FfiConverterBool.write(value.requiresAppleSilicon, into: &buf)
    }
}


public func FfiConverterTypeSttModelInfo_lift(_ buf: RustBuffer) throws -> SttModelInfo {
    return try FfiConverterTypeSttModelInfo.lift(buf)
}

public func FfiConverterTypeSttModelInfo_lower(_ value: SttModelInfo) -> RustBuffer {
    return FfiConverterTypeSttModelInfo.lower(value)
}


public struct TranscriptionChunk {
    public var text: String
    public var isFinal: Bool
    public var startTime: Double
    public var endTime: Double
    public var confidence: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, isFinal: Bool, startTime: Double, endTime: Double, confidence: Float) {
        self.text = text
        self.isFinal = isFinal
        self.startTime = startTime
        self.endTime = endTime
        self.confidence = confidence
    }
}



extension TranscriptionChunk: Equatable, Hashable {
    public static func ==(lhs: TranscriptionChunk, rhs: TranscriptionChunk) -> Bool {
        if lhs.text != rhs.text {
            return false
        }
        if lhs.isFinal != rhs.isFinal {
            return false
        }
        if lhs.startTime != rhs.startTime {
            return false
        }
        if lhs.endTime != rhs.endTime {
            return false
        }
        if lhs.confidence != rhs.confidence {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text)
        hasher.combine(isFinal)
        hasher.combine(startTime)
        hasher.combine(endTime)
        hasher.combine(confidence)
    }
}


public struct FfiConverterTypeTranscriptionChunk: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TranscriptionChunk {
        return
            try TranscriptionChunk(
                text: FfiConverterString.read(from: &buf), 
                isFinal: FfiConverterBool.read(from: &buf), 
                startTime: FfiConverterDouble.read(from: &buf), 
                endTime: FfiConverterDouble.read(from: &buf), 
                confidence: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: TranscriptionChunk, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterBool.write(value.isFinal, into: &buf)
        FfiConverterDouble.write(value.startTime, into: &buf)
        FfiConverterDouble.write(value.endTime, into: &buf)
        FfiConverterFloat.write(value.confidence, into: &buf)
    }
}


public func FfiConverterTypeTranscriptionChunk_lift(_ buf: RustBuffer) throws -> TranscriptionChunk {
    return try FfiConverterTypeTranscriptionChunk.lift(buf)
}

public func FfiConverterTypeTranscriptionChunk_lower(_ value: TranscriptionChunk) -> RustBuffer {
    return FfiConverterTypeTranscriptionChunk.lower(value)
}


public struct TranscriptionResult {
    public var text: String
    public var chunks: [TranscriptionChunk]
    public var durationSeconds: Double
    public var modelKey: String
    public var language: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, chunks: [TranscriptionChunk], durationSeconds: Double, modelKey: String, language: String) {
        self.text = text
        self.chunks = chunks
        self.durationSeconds = durationSeconds
        self.modelKey = modelKey
        self.language = language
    }
}



extension TranscriptionResult: Equatable, Hashable {
    public static func ==(lhs: TranscriptionResult, rhs: TranscriptionResult) -> Bool {
        if lhs.text != rhs.text {
            return false
        }
        if lhs.chunks != rhs.chunks {
            return false
        }
        if lhs.durationSeconds != rhs.durationSeconds {
            return false
        }
        if lhs.modelKey != rhs.modelKey {
            return false
        }
        if lhs.language != rhs.language {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text)
        hasher.combine(chunks)
        hasher.combine(durationSeconds)
        hasher.combine(modelKey)
        hasher.combine(language)
    }
}


public struct FfiConverterTypeTranscriptionResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TranscriptionResult {
        return
            try TranscriptionResult(
                text: FfiConverterString.read(from: &buf), 
                chunks: FfiConverterSequenceTypeTranscriptionChunk.read(from: &buf), 
                durationSeconds: FfiConverterDouble.read(from: &buf), 
                modelKey: FfiConverterString.read(from: &buf), 
                language: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: TranscriptionResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterSequenceTypeTranscriptionChunk.write(value.chunks, into: &buf)
        FfiConverterDouble.write(value.durationSeconds, into: &buf)
        FfiConverterString.write(value.modelKey, into: &buf)
        FfiConverterString.write(value.language, into: &buf)
    }
}


public func FfiConverterTypeTranscriptionResult_lift(_ buf: RustBuffer) throws -> TranscriptionResult {
    return try FfiConverterTypeTranscriptionResult.lift(buf)
}

public func FfiConverterTypeTranscriptionResult_lower(_ value: TranscriptionResult) -> RustBuffer {
    return FfiConverterTypeTranscriptionResult.lower(value)
}

fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionFloat: FfiConverterRustBuffer {
    typealias SwiftType = Float?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterFloat.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterFloat.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeChatMessage: FfiConverterRustBuffer {
    typealias SwiftType = [ChatMessage]

    public static func write(_ value: [ChatMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeChatMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ChatMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [ChatMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeChatMessage.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeSttModelInfo: FfiConverterRustBuffer {
    typealias SwiftType = [SttModelInfo]

    public static func write(_ value: [SttModelInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSttModelInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SttModelInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [SttModelInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSttModelInfo.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypeTranscriptionChunk: FfiConverterRustBuffer {
    typealias SwiftType = [TranscriptionChunk]

    public static func write(_ value: [TranscriptionChunk], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTranscriptionChunk.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TranscriptionChunk] {
        let len: Int32 = try readInt(&buf)
        var seq = [TranscriptionChunk]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTranscriptionChunk.read(from: &buf))
        }
        return seq
    }
}
public func getSession(sessionId: String) -> SttSession {
    return try!  FfiConverterTypeSttSession.lift(try! rustCall() {
    uniffi_voice_core_fn_func_get_session(
        FfiConverterString.lower(sessionId),$0
    )
})
}
public func infer(model: String, messages: [ChatMessage], temperature: Float?, maxTokens: UInt32?, baseUrl: String, apiKey: String) -> AiResponse {
    return try!  FfiConverterTypeAiResponse.lift(try! rustCall() {
    uniffi_voice_core_fn_func_infer(
        FfiConverterString.lower(model),
        FfiConverterSequenceTypeChatMessage.lower(messages),
        FfiConverterOptionFloat.lower(temperature),
        FfiConverterOptionUInt32.lower(maxTokens),
        FfiConverterString.lower(baseUrl),
        FfiConverterString.lower(apiKey),$0
    )
})
}
public func listAvailableModels() -> [SttModelInfo] {
    return try!  FfiConverterSequenceTypeSttModelInfo.lift(try! rustCall() {
    uniffi_voice_core_fn_func_list_available_models($0
    )
})
}
public func loadProviderConfigJson() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voice_core_fn_func_load_provider_config_json($0
    )
})
}
public func renderTemplate(templateName: String, context: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voice_core_fn_func_render_template(
        FfiConverterString.lower(templateName),
        FfiConverterString.lower(context),$0
    )
})
}
public func saveProviderConfigJson(json: String) {try! rustCall() {
    uniffi_voice_core_fn_func_save_provider_config_json(
        FfiConverterString.lower(json),$0
    )
}
}
public func startSttSession(modelKey: String, sampleRate: UInt32, language: String) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voice_core_fn_func_start_stt_session(
        FfiConverterString.lower(modelKey),
        FfiConverterUInt32.lower(sampleRate),
        FfiConverterString.lower(language),$0
    )
})
}
/**
 * Returns the path to the voice-hub directory (~/.voice-hub/)
 */
public func voiceHubDir() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voice_core_fn_func_voice_hub_dir($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_voice_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_voice_core_checksum_func_get_session() != 10505) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_func_infer() != 11326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_func_list_available_models() != 65096) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_func_load_provider_config_json() != 65368) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_func_render_template() != 27840) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_func_save_provider_config_json() != 11202) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_func_start_stt_session() != 2482) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_func_voice_hub_dir() != 15958) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_buffer_duration_seconds() != 41759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_chunk_count() != 61271) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_finalize() != 19250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_id() != 12157) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_model_key() != 1601) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_process_chunk() != 15857) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_reset() != 6917) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_set_chunk() != 39623) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voice_core_checksum_method_sttsession_status() != 64332) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all